### PR TITLE
proposal: import just/ujust shortcuts system from Bazzite into nobara-just (njust) package

### PR DESCRIPTION
**Pull request by matte-schwartz**
A suggestion I've seen from newer users to Nobara, especially on handhelds, is that there should be an easier way to set up extra functionality like precise TDP control or Decky Loader and some device-specific themes for their hardware. Instead of users relying on third-party scripts that have them install packages in an inconsistent manner, lets simplify this by instituting a njust command shortcuts.

Instead of adding a .justfile to the user's home directory like upstream just, this creates an njust alias with a set of customized commands just for Nobara.
image

I owe the bulk of this project to Bazzite, who figured this entire alias system out to work around upstream issues with just. While some of our commands remain the same, I have built out new logging options for common troubleshooting logs directly to centos with fpaste.  I have also expanded the Deck image just file options by adding removal commands to go with every install command.

In the future, I'd like to substitute fpaste for pbcli, which will let us hook log upload up directly to paste.gloriouseggroll.tv. I'm waiting on this issue to be implemented before doing so: https://github.com/Mydayyy/pbcli/issues/2

There is also way more that can be done with just files in the future, but for now I wanted to stay with a list of simple commands I could fully test and evaluate for myself. The only downsides that I can see are the inherent issues you bring along with installing some of these packages like Decky Loader and associated plug-ins that rely on Steam integration. I do not see any downsides to the logging upload commands or other shortcuts it offers.

There is an RPM available for testing here: https://copr.fedorainfracloud.org/coprs/matte-schwartz/random-testing/package/nobara-just/ 

Let me know if you have any feedback. and no worries if you want to put this on the backburner for now. Thank you again to the wonderful dev team at Bazzite for letting me adapt this to Nobara and offering some pointers along the way!

### CODE REVIEW

**Comment by Mydayyy** [comment]
Greetings,

I was made aware of this merge request by the crosslink over at pbcli. I came with a question regarding the feature you are currently waiting on.

That feature implements a (potential) required user interaction if the given  file is larger than the specified size limit. In the context of this PR would that work? Since if using the pbcli in a non-interactive way the flag would not have much use apart from just aborting the upload process without asking the user. The currently used fpaste here does not appear to have such a filesize limit.

I'm to make sure that I understood the feature request correctly.

Best Regards
Mydayyy

**Comment by matte-schwartz** [comment]
@Mydayyy thank you very much for your response and to the original feature request submitter. 

I double checked and it seems like the [custom pastebin ](https://paste.gloriouseggroll.tv/) in question has a file size limit already that will cause a failure over a certain file size, so the flag may be unnecessary in this specific scenario. 

what I do think would still be useful is a warning like `fpaste` has that warns a user if a file size may be too large for the pastebin to accept or appears to be binary rather than text, and to expect server errors: https://pagure.io/fpaste/blob/main/f/fpaste#_195

**Comment by GloriousEggroll** [comment]
I havent forgotten about this I just need time to test it/mess with it before deciding whether or not to pull it in and/or giving any reasons not to

**Comment by matte-schwartz** [comment]
honestly I think most of what I outlined here could live in the new Nobara welcome and be a better experience for users. I was thinking of just giving that a try instead after seeing how nicely the driver manager works so far.

**Comment by matte-schwartz** [comment]
closing in favor of potential refactor into Nobara Welcome

**Pull request closed without merging**
